---
language: python
services: docker

env:
  global:
    - COLLECTION_NAMESPACE: ripclawffb
    - COLLECTION_NAME: helix_core
  matrix:
    - MOLECULE_DISTRO: default

install:
  # Install test dependencies.
  - pip install ansible molecule docker

before_script:
  # Move the collection into the required path.
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-${COLLECTION_NAME/_/-} ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Test helix modules
  - molecule test
