---
sudo: required
language: python
python:
  - 3.8
services: docker

before_install:
  - sudo apt-get -qq update
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

env:
  global:
    - COLLECTION_NAMESPACE: ripclawffb
    - COLLECTION_NAME: helix_core
  matrix:
    - MOLECULE_DISTRO: default

install:
  # Install test dependencies.
  - python3 -m pip install pipenv
  - pipenv install

before_script:
  # Move the collection into the required path.
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-${COLLECTION_NAME/_/-} ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Test helix modules
  - molecule test
