---
sudo: required
language: python
python:
  - 3.8
services: docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - COLLECTION_NAMESPACE: ripclawffb
    - COLLECTION_NAME: helix_core
  matrix:
    - MOLECULE_DISTRO: default

install:
  # Install test dependencies.
  - python3 -m pip install pipenv
  - pipenv install

before_script:
  # Move the collection into the required path.
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-${COLLECTION_NAME/_/-} ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

jobs:
  include:
    - stage: test
      script:
        # Test helix modules
        - molecule test
    # Define the release stage that runs semantic-release
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          # Use nvm to install and use the Node LTS version (nvm is installed on all Travis images)
          - nvm install lts/*
          - npx semantic-release -d
