---
authors:
  - Asif Shaikh
dependencies: {}
description: A collection of roles and modules to manage Perforce Helix Core
documentation: 'https://github.com/ripclawffb/ansible-collection-helix-core'
issues: 'https://github.com/ripclawffb/ansible-collection-helix-core'
license:
  - MIT
name: helix_core
namespace: ripclawffb
readme: README.md
repository: 'https://github.com/ripclawffb/ansible-collection-helix-core'
tags:
  - helix
  - core
  - perforce
  - p4
  - p4d
version: 1.0.1
# homepage: ''
