---
authors:
  - Asif Shaikh
dependencies: {}
description: A collection of modules to manage Perforce Helix Core
documentation: 'https://ripclawffb.github.io/ansible-collection-helix-core/collections/index_module.html'
issues: 'https://github.com/ripclawffb/ansible-collection-helix-core/issues'
license:
  - MIT
name: helix_core
namespace: ripclawffb
readme: README.md
repository: 'https://github.com/ripclawffb/ansible-collection-helix-core'
tags:
  - helix
  - core
  - perforce
  - p4
  - p4d
version: 1.0.6
homepage: 'https://galaxy.ansible.com/ui/repo/published/ripclawffb/helix_core/'
build_ignore:
  - '.cache'
  - '.github'
  - '.vscode'
  - 'rst'
