---
- name: Converge
  hosts: all

  collections:
    - ripclawffb.helix_core

  tasks:
    - name: import helix_core_configurable tasks
      import_tasks: ../../test/integration/targets/helix_core_configurable/tasks/main.yml

    - name: import helix_core_client tasks
      import_tasks: ../../test/integration/targets/helix_core_client/tasks/main.yml

    - name: import helix_core_user tasks
      import_tasks: ../../test/integration/targets/helix_core_user/tasks/main.yml
