---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos:7
    command: '-r .'
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATHS: "/home/travis/build/ripclawffb:~/.ansible/collections"
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: "/usr/bin/python3"
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - destroy
