---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    dockerfile: Dockerfile.centos.7.j2
    image: centos:7
    command: '-r .'
  - name: ubuntu1804
    dockerfile: Dockerfile.ubuntu.18.04.j2
    image: ubuntu:18.04
    command: '-r .'
  - name: ubuntu2004
    dockerfile: Dockerfile.ubuntu.20.04.j2
    image: ubuntu:20.04
    command: '-r .'
provisioner:
  name: ansible
  log: true
  # options:
  #   vvv: true
  env:
    ANSIBLE_COLLECTIONS_PATHS: "/home/runner/work/ansible-collection-helix-core/ansible-collection-helix-core:~/.ansible/collections"
  inventory:
    host_vars:
      centos7:
        ansible_python_interpreter: "/usr/bin/python3"
      ubuntu:
        ansible_python_interpreter: "/usr/bin/python3"
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - destroy
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
